### PR TITLE
Fixed should not render when data-source is empty (fixes #95)

### LINKED ISSUE #95: renderItem() should not be called when `fullLength === 0`

### PR DESCRIPTION
**Pull request by wilsonpage**

### CODE REVIEW

File: test/fast-list-test.js [hunk 1]
```diff
@@ -190,6 +190,58 @@ suite('FastList >', function() {
...
+      });
+
+      suite('remove all items again', function() {
+        setup(function() {
+          source.data = [];
+          source.populateItem.reset();
+          return fastList.reloadData();
+        });
+
+        test('it does not render anytihng and hides all items', function() {
```
Comment (etiennesegonzac) [inline test/fast-list-test.js]: `s/anytihng/anything`
